spring:
  application:
    name: notification-service
  config:
    import: "optional:configserver:http://config-server:8888"

logging:
  level:
    com.imbuy.notification: DEBUG
    org.springframework.kafka: INFO

