spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-swagger
          uri: lb://user-service
          predicates:
            - Path=/users/v3/api-docs
          filters:
            - StripPrefix=1

        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0

        - id: user-service-all
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=0

        - id: category-service-swagger
          uri: lb://category-service
          predicates:
            - Path=/categories/v3/api-docs
          filters:
            - StripPrefix=1

        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/categories/**
          filters:
            - StripPrefix=0

        # Lot Service
        - id: lot-service-swagger
          uri: lb://lot-service
          predicates:
            - Path=/lots/v3/api-docs
          filters:
            - StripPrefix=1

        - id: lot-service
          uri: lb://lot-service
          predicates:
            - Path=/lots/**
          filters:
            - StripPrefix=0

        # Bid Service
        - id: bid-service-swagger
          uri: lb://bid-service
          predicates:
            - Path=/bids/v3/api-docs
          filters:
            - StripPrefix=1

        - id: bid-service
          uri: lb://bid-service
          predicates:
            - Path=/bids/**
          filters:
            - StripPrefix=0
        - id: file-service-swagger
          uri: lb://file-service
          predicates:
            - Path=/files/v3/api-docs
          filters:
            - StripPrefix=1

        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/files/**
          filters:
            - StripPrefix=0
        - id: notification-ws
          uri: lb://notification-service
          predicates:
            - Path=/ws/**

        - id: notification-service-swagger
          uri: lb://notification-service
          predicates:
            - Path=/notifications/v3/api-docs
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
          filters:
            - StripPrefix=0


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway
      - url: /users/v3/api-docs
        name: User Service
      - url: /categories/v3/api-docs
        name: Category Service
      - url: /lots/v3/api-docs
        name: Lot Service
      - url: /bids/v3/api-docs
        name: Bid Service
      - url: /files/v3/api-docs
        name: File Service
      - url: /notifications/v3/api-docs
        name: Notification Service